// A real history to lay out: 150 commits over main and develop with 29 merges —
// pull requests merged with --no-ff, release merges into main, a hotfix merged
// both ways, a develop-into-feature back-merge, a revert, tags, remote-tracking
// branches and two linked worktrees' branches — listed as `git log --topo-order
// --branches --remotes --tags HEAD` lists it, child first. HEAD is develop.
//
// [sha, parents, author, subject, local branches, remote branches, tags]
import type { LogCommit } from "../git-graph-layout";

type Row = [string, string[], string, string, string[], string[], string[]];

export const HISTORY_HEAD = "eb7170c";

const ROWS: Row[] = [
  ["eb7170c",["ce73d51"],"Alex Morgan","test(api): pin half-up rounding",["develop"],[],[]],
  ["ce73d51",["ebe97fb"],"Alex Morgan","fix(api): round currency half-up in totals",[],[],[]],
  ["c66f14c",["4402065"],"Alex Morgan","test(auth): cover login failures and the cookie",["feature/auth-login"],[],[]],
  ["4402065",["65fecee"],"Alex Morgan","feat(auth): issue a session cookie on login",[],[],[]],
  ["65fecee",["bb50a24"],"Alex Morgan","feat(auth): add login route with password check",[],["origin/feature/auth-login"],[]],
  ["bb50a24",["dbebcb9"],"Alex Morgan","docs(auth): describe the login flow",[],[],[]],
  ["1609921",["ebe97fb"],"Alex Morgan","fix(api): cap retry backoff at 30s",["fix/retry-backoff"],[],[]],
  ["ab9d31e",["ebe97fb"],"Mei Lin","fix(portal): keep sessions alive on slow networks",[],["origin/develop"],[]],
  ["ebe97fb",["908be5d"],"Jonas Weber","chore(ci): run tests on Node 24",[],[],["deploy/staging"]],
  ["908be5d",["2f2c90d"],"Priya Nair","docs(api): add README badges",[],[],[]],
  ["2f2c90d",["dbebcb9","4313bfc"],"Jonas Weber","Merge pull request #35 from shopco/fix/cart-rounding-display",[],[],[]],
  ["4313bfc",["dd4e0ff"],"Tomás Ortega","test(cart): drawer shows two decimals",[],[],[]],
  ["dd4e0ff",["1575bf5"],"Tomás Ortega","fix(cart): show rounded totals in the cart drawer",[],[],[]],
  ["dbebcb9",["1a164cf","0c0222a"],"Jonas Weber","Merge pull request #33 from shopco/feature/payments-v2",[],[],[]],
  ["0c0222a",["a4d12b3"],"Jonas Weber","docs(payments): migration notes for v2",[],["origin/feature/payments-v2"],[]],
  ["a4d12b3",["d6f1519"],"Jonas Weber","test(payments): intent state machine",[],[],[]],
  ["d6f1519",["e341b0d"],"Jonas Weber","fix(payments): treat provider timeouts as retryable",[],[],[]],
  ["e341b0d",["ad16c6e","1a164cf"],"Jonas Weber","Merge branch 'develop' into feature/payments-v2",[],[],[]],
  ["1a164cf",["1575bf5"],"dependabot[bot]","chore(deps): bump pg from 8.13.1 to 8.16.3",[],[],[]],
  ["ad16c6e",["99f5737"],"Jonas Weber","feat(payments): idempotency keys on create",[],[],[]],
  ["99f5737",["1575bf5"],"Jonas Weber","feat(payments): new payment intent flow",[],[],[]],
  ["baec596",["f0936dd"],"Alex Morgan","test(invoice): builder snapshots",[],["origin/feature/bargan/VCRM-9090-make-the-invoice-builder-understand-everything"],[]],
  ["f0936dd",["c82f291"],"Alex Morgan","feat(invoice): understand free-text instructions",[],[],[]],
  ["c82f291",["3c5e608"],"Alex Morgan","feat(invoice): line items with tax groups",[],[],[]],
  ["3c5e608",["1575bf5"],"Alex Morgan","feat(invoice): invoice builder skeleton",[],[],[]],
  ["4270c7c",["063baa8"],"Mei Lin","wip: resolvers for products",[],["origin/feature/graphql-spike"],[]],
  ["063baa8",["1575bf5"],"Mei Lin","feat(api): graphql schema spike",[],[],[]],
  ["6bc901a",["f0a53f0","1575bf5"],"Jonas Weber","Merge branch 'develop' for release v1.4.0",["main"],["origin/main"],["v1.4.0"]],
  ["1575bf5",["2cf78ea"],"Jonas Weber","chore(release): v1.4.0",[],[],[]],
  ["2cf78ea",["c66b638"],"Mei Lin","chore: add an editorconfig",[],[],[]],
  ["c66b638",["9589b83","5264db4"],"Jonas Weber","Merge pull request #31 from shopco/chore/typescript-strict",[],[],[]],
  ["5264db4",["7bc7bb2"],"Jonas Weber","test(types): strict helpers",[],[],[]],
  ["7bc7bb2",["d3a9aae"],"Jonas Weber","refactor(types): narrow request bodies with zod",[],[],[]],
  ["d3a9aae",["c4a70cf"],"Jonas Weber","chore(types): turn on noUncheckedIndexedAccess",[],[],[]],
  ["9589b83",["6d52e26","a48cc3a"],"Jonas Weber","Merge pull request #30 from shopco/feature/search-synonyms",[],[],[]],
  ["a48cc3a",["40705fc"],"Priya Nair","fix(catalog): lowercase synonyms on save",[],[],[]],
  ["40705fc",["e6ad775"],"Priya Nair","test(catalog): synonyms expand queries",[],[],[]],
  ["e6ad775",["2eb15e9"],"Priya Nair","feat(catalog): admin endpoint to edit synonyms",[],[],[]],
  ["2eb15e9",["c4a70cf"],"Priya Nair","feat(catalog): synonym table for search",[],[],[]],
  ["6d52e26",["4035a8c"],"dependabot[bot]","chore(deps): bump zod from 3.25.0 to 3.25.76",[],[],[]],
  ["4035a8c",["a950af7","c5d1968"],"Jonas Weber","Merge pull request #29 from shopco/feature/inventory-sync",[],[],[]],
  ["c5d1968",["329eb2a"],"Priya Nair","perf(inventory): batch writes in groups of 500",[],["origin/feature/inventory-sync"],[]],
  ["329eb2a",["05f00f5"],"Priya Nair","test(inventory): reconciliation with partial data",[],[],[]],
  ["05f00f5",["ac8a3da"],"Priya Nair","fix(inventory): skip SKUs the warehouse marks discontinued",[],[],[]],
  ["ac8a3da",["8ed679b"],"Priya Nair","feat(inventory): reconcile stock levels",[],[],[]],
  ["8ed679b",["c4a70cf"],"Priya Nair","feat(inventory): nightly sync from the warehouse API",[],[],[]],
  ["a950af7",["ccdeb23","d26824d"],"Jonas Weber","Merge pull request #28 from shopco/fix/portal-csrf",[],[],[]],
  ["d26824d",["b52604a"],"Mei Lin","test(portal): reject posts without a token",[],["origin/fix/portal-csrf"],[]],
  ["b52604a",["c4a70cf"],"Mei Lin","fix(portal): require a CSRF token on form posts",[],[],[]],
  ["ccdeb23",["c467009"],"Jonas Weber","chore(ci): cache npm between jobs",[],[],[]],
  ["c467009",["c4a70cf","8abca94"],"Jonas Weber","Merge pull request #27 from shopco/feature/i18n-errors",[],[],[]],
  ["8abca94",["cd86878"],"Tomás Ortega","test(i18n): every error key exists in every catalog",[],[],[]],
  ["cd86878",["b14c0d7"],"Tomás Ortega","fix(i18n): fall back to English for unknown locales",[],[],[]],
  ["b14c0d7",["99fe144"],"Tomás Ortega","feat(i18n): Spanish and Romanian catalogs",[],[],[]],
  ["99fe144",["c4a70cf"],"Tomás Ortega","feat(i18n): translatable error messages",[],[],[]],
  ["f0a53f0",["80ffb2c","c4a70cf"],"Jonas Weber","Merge branch 'develop' for release v1.3.0",[],[],["v1.3.0"]],
  ["c4a70cf",["a27d472"],"Jonas Weber","chore(release): v1.3.0",[],[],[]],
  ["a27d472",["26f7223"],"Jonas Weber","Revert \"perf(db): reuse prepared statements\"",[],[],[]],
  ["26f7223",["1a587c8"],"Mei Lin","style: format with prettier 3.6",[],[],[]],
  ["1a587c8",["25c2668","0fe4153"],"Jonas Weber","Merge pull request #23 from shopco/chore/deps-2026-08",[],[],[]],
  ["0fe4153",["06a4f2e"],"Jonas Weber","chore(deps): drop the unused nanoid-dev",[],[],[]],
  ["06a4f2e",["aa9a55a"],"Jonas Weber","chore(deps): update eslint plugins",[],[],[]],
  ["aa9a55a",["7a9b880"],"Jonas Weber","chore(deps): update typescript to 5.9",[],[],[]],
  ["25c2668",["ce1b9ab","fd36825"],"Jonas Weber","Merge pull request #22 from shopco/feature/metrics",[],[],[]],
  ["fd36825",["169fe62"],"Mei Lin","docs(metrics): list the exported metrics",[],["origin/feature/metrics"],[]],
  ["169fe62",["c74539f"],"Mei Lin","docs(metrics): latency analysis notebook",[],[],[]],
  ["c74539f",["65c5474"],"Mei Lin","fix(metrics): guard label cardinality",[],[],[]],
  ["65c5474",["1f70d06"],"Mei Lin","feat(metrics): p95 latency histogram",[],[],[]],
  ["1f70d06",["7a9b880"],"Mei Lin","feat(metrics): expose request counters",[],[],[]],
  ["ce1b9ab",["092113d"],"Tomás Ortega","fix(api): return 404 JSON for unknown routes",[],[],[]],
  ["092113d",["7a9b880","c5c8ffa"],"Jonas Weber","Merge pull request #21 from shopco/feature/admin-audit-log",[],[],[]],
  ["c5c8ffa",["de67333"],"Priya Nair","test(admin): audit entries are append-only",[],[],[]],
  ["de67333",["bbf32db"],"Priya Nair","feat(admin): export the audit log",[],[],[]],
  ["bbf32db",["ed8be66"],"Priya Nair","feat(admin): filter the audit log by actor and date",[],[],[]],
  ["ed8be66",["7a9b880"],"Priya Nair","feat(admin): record admin actions in an audit log",[],[],[]],
  ["80ffb2c",["8adb6f5","7a9b880"],"Jonas Weber","Merge branch 'develop' for release v1.2.0",[],[],["v1.2.0"]],
  ["7a9b880",["f51fdb4"],"Jonas Weber","chore(release): v1.2.0",[],[],[]],
  ["f51fdb4",["6037cc7"],"Jonas Weber","docs: contributing guide",[],[],[]],
  ["6037cc7",["12af024"],"dependabot[bot]","chore(deps): bump vitest from 3.2.0 to 3.2.4",[],[],[]],
  ["12af024",["821cf62","34fe7e1"],"Jonas Weber","Merge pull request #17 from shopco/fix/export-timezone",[],[],[]],
  ["34fe7e1",["fd11295"],"Tomás Ortega","test(orders): DST boundaries in exports",[],[],[]],
  ["fd11295",["d4c7ba0"],"Tomás Ortega","fix(orders): export timestamps in the shop's timezone",[],[],[]],
  ["821cf62",["95009d9","26d7421"],"Jonas Weber","Merge pull request #16 from shopco/refactor/db-pool",[],[],[]],
  ["26d7421",["45da1d2"],"Jonas Weber","test(db): pool exhaustion recovers",[],[],[]],
  ["45da1d2",["60a07e2"],"Jonas Weber","perf(db): reuse prepared statements",[],[],[]],
  ["60a07e2",["d4c7ba0"],"Jonas Weber","refactor(db): extract pool configuration",[],[],[]],
  ["95009d9",["06c8ba1"],"Priya Nair","docs: add an architecture diagram",[],[],[]],
  ["06c8ba1",["49bd9ac","8a8d1e0"],"Jonas Weber","Merge pull request #15 from shopco/fix/currency-rounding",[],[],[]],
  ["8a8d1e0",["eb92444"],"Mei Lin","test(cart): rounding cases from the support tickets",[],[],[]],
  ["eb92444",["d4c7ba0"],"Mei Lin","fix(cart): round each line before summing",[],[],[]],
  ["49bd9ac",["d4c7ba0","dd2a11b"],"Jonas Weber","Merge pull request #14 from shopco/feature/webhooks",[],[],[]],
  ["dd2a11b",["f4fecbd"],"Tomás Ortega","docs(webhooks): how to verify a signature",[],[],[]],
  ["f4fecbd",["3f8d854"],"Tomás Ortega","fix(webhooks): compare signatures in constant time",[],[],[]],
  ["3f8d854",["4d1d284"],"Tomás Ortega","test(webhooks): signature verification vectors",[],[],[]],
  ["4d1d284",["7ed6b56"],"Tomás Ortega","feat(webhooks): dead-letter queue for exhausted retries",[],[],[]],
  ["7ed6b56",["ab35cc6"],"Tomás Ortega","feat(webhooks): retry failed deliveries with backoff",[],[],[]],
  ["ab35cc6",["d4c7ba0"],"Tomás Ortega","feat(webhooks): sign outgoing webhooks with HMAC",[],[],[]],
  ["d4c7ba0",["ce69c5f","1df6979"],"Tomás Ortega","Merge branch 'hotfix/1.1.1' into develop",[],[],[]],
  ["8adb6f5",["d438c78","1df6979"],"Tomás Ortega","Merge branch 'hotfix/1.1.1'",[],[],["v1.1.1"]],
  ["1df6979",["b115cae"],"Tomás Ortega","chore(release): v1.1.1",[],[],[]],
  ["b115cae",["d438c78"],"Tomás Ortega","fix(portal): do not log session tokens",[],[],[]],
  ["d438c78",["a367a5a","ce69c5f"],"Jonas Weber","Merge branch 'develop' for release v1.1.0",[],[],["v1.1.0"]],
  ["ce69c5f",["709bb7c"],"Jonas Weber","chore(release): v1.1.0",[],[],[]],
  ["709bb7c",["a3ba0b8","d66009d"],"Jonas Weber","Merge pull request #11 from shopco/feature/product-images",[],[],[]],
  ["d66009d",["9660cc7"],"Mei Lin","test(catalog): resized images stay under 200 KB",[],["origin/feature/product-images"],[]],
  ["9660cc7",["b0fda4e"],"Mei Lin","fix(catalog): keep the original aspect ratio",[],[],[]],
  ["b0fda4e",["1218fe6"],"Mei Lin","feat(catalog): resize images to three sizes",[],[],[]],
  ["1218fe6",["ef40e21"],"Mei Lin","feat(catalog): product image upload",[],[],[]],
  ["a3ba0b8",["97fbf4e","534dc0c"],"Jonas Weber","Merge pull request #10 from shopco/feature/rate-limit",[],[],[]],
  ["534dc0c",["a05568f"],"Priya Nair","refactor(api): share the clock between limiter and retry",[],[],[]],
  ["a05568f",["7ec5a59"],"Priya Nair","test(api): limiter under burst load",[],[],[]],
  ["7ec5a59",["1f31c05"],"Priya Nair","fix(api): reset buckets on config reload",[],[],[]],
  ["1f31c05",["a0254f2"],"Priya Nair","feat(api): per-key limits from config",[],[],[]],
  ["a0254f2",["ef40e21"],"Priya Nair","feat(api): add a token-bucket rate limiter",[],[],[]],
  ["97fbf4e",["bbb175c","3b3dce9"],"Jonas Weber","Merge pull request #9 from shopco/fix/portal-timeout",[],[],[]],
  ["3b3dce9",["9c17776"],"Mei Lin","test(portal): session expiry warning",[],[],[]],
  ["9c17776",["ee8b41f"],"Mei Lin","fix(portal): warn two minutes before the session expires",[],[],[]],
  ["ee8b41f",["ef40e21"],"Mei Lin","fix(portal): extend the session timeout to 30 minutes",[],[],[]],
  ["bbb175c",["93e321b","ce1b948"],"Jonas Weber","Merge pull request #8 from shopco/feature/orders-export",[],[],[]],
  ["ce1b948",["ef6db4d"],"Jonas Weber","docs(orders): document the export endpoint",[],[],[]],
  ["ef6db4d",["5e7a75b"],"Jonas Weber","test(orders): export of 10k orders stays under 200 MB",[],[],[]],
  ["5e7a75b",["d71bad9"],"Jonas Weber","fix(orders): quote fields that contain commas",[],[],[]],
  ["d71bad9",["23fbae3"],"Jonas Weber","feat(orders): stream large exports instead of buffering",[],[],[]],
  ["23fbae3",["ef40e21"],"Jonas Weber","feat(orders): export orders as CSV",[],[],[]],
  ["93e321b",["ef40e21"],"dependabot[bot]","chore(deps): bump express from 4.21.2 to 4.22.0",[],[],[]],
  ["a367a5a",["a369b73","ef40e21"],"Jonas Weber","Merge branch 'develop' for release v1.0.0",[],[],["v1.0.0"]],
  ["ef40e21",["e9da1a3"],"Jonas Weber","chore(release): v1.0.0",[],[],[]],
  ["e9da1a3",["fc66c74"],"Jonas Weber","docs: describe local setup in the README",[],[],[]],
  ["fc66c74",["63cf4dd","2ea9773"],"Jonas Weber","Merge pull request #5 from shopco/chore/eslint-setup",[],[],[]],
  ["2ea9773",["79401a0"],"Mei Lin","ci: run lint in the pipeline",[],[],[]],
  ["79401a0",["5732613"],"Mei Lin","chore: fix lint errors in src/db",[],[],[]],
  ["5732613",["a369b73"],"Mei Lin","chore: add eslint and prettier configs",[],[],[]],
  ["63cf4dd",["8b7cac6","c431a45"],"Jonas Weber","Merge pull request #4 from shopco/feature/cart-totals",[],[],[]],
  ["c431a45",["725a87d"],"Tomás Ortega","fix(cart): never let a discount push the total below zero",[],[],[]],
  ["725a87d",["8b07e2d"],"Tomás Ortega","test(cart): totals for mixed currencies",[],[],[]],
  ["8b07e2d",["87c9142"],"Tomás Ortega","feat(cart): apply discount codes",[],[],[]],
  ["87c9142",["a369b73"],"Tomás Ortega","feat(cart): compute cart totals with tax",[],[],[]],
  ["8b7cac6",["a369b73","14dc893"],"Jonas Weber","Merge pull request #3 from shopco/feature/catalog-search",[],[],[]],
  ["14dc893",["6321a3a"],"Priya Nair","feat(catalog): paginate search with cursors",[],[],[]],
  ["6321a3a",["9c7afab"],"Priya Nair","fix(catalog): escape LIKE wildcards in search terms",[],[],[]],
  ["9c7afab",["223b708"],"Priya Nair","test(catalog): cover empty and accented queries",[],[],[]],
  ["223b708",["cda8a8b"],"Priya Nair","feat(catalog): rank results by title match",[],[],[]],
  ["cda8a8b",["a369b73"],"Priya Nair","feat(catalog): add product search endpoint",[],[],[]],
  ["a369b73",["f386117"],"Priya Nair","feat(api): generate API types from the OpenAPI spec",[],[],[]],
  ["f386117",["d1e2654"],"Jonas Weber","chore(deps): commit the lockfile",[],[],[]],
  ["d1e2654",["695d954"],"Mei Lin","chore: add product fixtures and the logo",[],[],[]],
  ["695d954",["29b1513"],"Tomás Ortega","feat(api): money helpers for cart totals",[],[],[]],
  ["29b1513",["6813354"],"Priya Nair","feat(auth): signed tokens for password resets",[],[],[]],
  ["6813354",["cfca548"],"Jonas Weber","feat(api): log every request at debug level",[],[],[]],
  ["cfca548",[],"Jonas Weber","chore: initial commit",[],[],[]],
];

/** The history as `/api/git/log` answers it, newest first, at a fixed time. */
export function shopHistory(limit = ROWS.length): LogCommit[] {
  return ROWS.slice(0, limit).map(([sha, parents, name, subject, local, remote, tags], i) => ({
    sha,
    parents,
    author: { name, email: `${name.toLowerCase().replace(/[^a-z]+/g, ".")}@example.com` },
    date: new Date(Date.UTC(2026, 9, 5, 16) - i * 3_600_000).toISOString(),
    subject,
    trailers: [],
    refs: { local, remote, tags, head: sha === HISTORY_HEAD },
    agent: null,
  }));
}
